[build]
buildCommand = "npx prisma generate && npm run build"

[deploy]
preDeployCommand = ["npx prisma migrate deploy"]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
